### GET
GET http://localhost:3000/api/getCoffeeStoreById?id=54e3e299498e7c46e1f7974b

### POST
POST http://localhost:3000/api/createCoffeeStore
Content-Type: application/json

{
  "id": "7",
  "name": "coffee name",
  "address": "coffee address",
  "neighbourhood": "coffee ne",
  "vote": 5,
  "imgUrl": "img url"
}

### DELETE
DELETE https://jsonplaceholder.typicode.com/posts/1

### PATCH
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
    "title":"new pathched title",
    "body": "new patched body"
}