### GET

### POST
POST http://localhost:3000/api/createCoffeeStore
Content-Type: application/json

{
  "id": ""
  
}

### DELETE
DELETE https://jsonplaceholder.typicode.com/posts/1

### PATCH
PUT https://jsonplaceholder.typicode.com/posts/1
Content-Type: application/json

{
    "title":"new pathched title",
    "body": "new patched body"
}